### ISSUE TITLE
variation-normalizer does not work for some NM HGVS expressions

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/architecture#542]
Not sure if any NM expressions work. Just seeing some log errors that some don't. The log message comes from the psql library and says a relation is missing, so maybe the UTA initialization code is missing a step. We do remove the `refresh materialized views` from the initialization, but I don't think removing this should make the view not exist.

The example below fails on our deployment but succeeds on `normalize.cancervariants.org`

`NM_173354.5:c.1154G>A`

log:
```
INFO:     127.0.0.1:60456 - "GET /variation/to_canonical_variation?q=NM_173354.5%3Ac.1154G%3EA&fmt=hgvs&complement=false&do_liftover=false&hgvs_dup_del_mode=default&untranslatable_returns_text=false HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/applications.py", line 125, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "./variation/main.py", line 356, in to_canonical_variation
    resp = await query_handler.to_canonical_handler.to_canonical_variation(
  File "./variation/to_canonical_variation.py", line 99, in to_canonical_variation
    variation, warnings = await self.hgvs_to_canonical_variation(
  File "./variation/to_canonical_variation.py", line 277, in hgvs_to_canonical_variation
    validations = await self.validator.perform(
  File "./variation/validators/validate.py", line 120, in perform
    results = await validator.validate(
  File "./variation/validators/validator.py", line 208, in validate
    await self.get_valid_invalid_results(
  File "./variation/validators/coding_dna_substitution.py", line 74, in get_valid_invalid_results
    cds_start_end = await self.uta.get_cds_start_end(t)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/cool_seq_tool/data_sources/uta_database.py", line 483, in get_cds_start_end
    cds_start_end = await self.execute_query(query)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/cool_seq_tool/data_sources/uta_database.py", line 157, in execute_query
    result = await _execute_query(query)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/cool_seq_tool/data_sources/uta_database.py", line 151, in _execute_query
    r = await connection.fetch(q)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/asyncpg/connection.py", line 620, in fetch
    return await self._execute(
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/asyncpg/connection.py", line 1658, in _execute
    result, _ = await self.__execute(
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/asyncpg/connection.py", line 1683, in __execute
    return await self._do_execute(
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/asyncpg/connection.py", line 1718, in _do_execute
    stmt = await self._get_statement(
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/asyncpg/connection.py", line 397, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 168, in prepare
asyncpg.exceptions.UndefinedTableError: relation "uta_20210129.transcript" does not exist
```

**Comment by korikuzma** [comment]
@theferrit32 I agree that the skipping the `REFRESH MATERIALIZED VIEWS` should not affect this. We skip these on our side as well.

**Comment by theferrit32** [comment]
The issue was I had a mismatch between the schema name segment in the `UTA_DB_URL` environment variable set for the variation-normalization code, and the `UTA_VERSION` used by the UTA setup.

Fix included here:
https://github.com/clingen-data-model/architecture/commit/f25bd85df0beec48f652605d72cc9ef82610c3fd
