### ISSUE TITLE
Variation normalizer filenotfound exception in parsed_to_abs_cnv

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/architecture#548]
```
INFO:     35.191.28.32:53524 - "GET /variation/to_canonical_variation?q=NC_000002.12%3Ag.47799972T%3EG&fmt=hgvs&untranslatable_returns_text=true HTTP/1.1" 200 OK
INFO:     35.191.18.157:54885 - "GET /variation/to_canonical_variation?q=NC_000017.11%3Ag.76473245G%3EA&fmt=hgvs&untranslatable_returns_text=true HTTP/1.1" 200 OK
INFO:     130.211.1.206:54353 - "GET /variation/parsed_to_abs_cnv?untranslatable_returns_text=true&assembly=GRCh37&chr=16&start=6910132&end=7211575&total_copies=1 HTTP/1.1" 200 OK
INFO:     35.191.28.33:59999 - "GET /variation/parsed_to_abs_cnv?untranslatable_returns_text=true&assembly=GRCh37&chr=3&start=58782604&end=58807458&total_copies=0 HTTP/1.1" 200 OK
[E::bgzf_uncompress] Inflate operation failed: invalid distance too far back
[E::fai_retrieve] Failed to retrieve block. (Seeking in a compressed, .gzi unindexed, file?)
INFO:     35.191.1.252:51910 - "GET /variation/parsed_to_abs_cnv?untranslatable_returns_text=true&assembly=GRCh37&chr=15&start=71597090&end=71853137&total_copies=1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "./variation/main.py", line 584, in parsed_to_abs_cnv
    resp = query_handler.to_copy_number_handler.parsed_to_abs_cnv(
  File "./variation/to_copy_number_variation.py", line 263, in parsed_to_abs_cnv
    self.seqrepo_access.seqrepo_client[accession][end]
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/biocommons/seqrepo/seqrepo.py", line 55, in __getitem__
    return self._fetch(key.start, key.stop)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/biocommons/seqrepo/seqrepo.py", line 42, in _fetch
    return self._sr.sequences.fetch(seq_id, start, end)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/biocommons/seqrepo/fastadir/fastadir.py", line 122, in fetch
    return fabgz.fetch(seq_id, start, end)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/biocommons/seqrepo/fastadir/fabgz.py", line 67, in fetch
    return self._fh.fetch(seq_id.encode("ascii"), start, end)
  File "pysam/libcfaidx.pyx", line 317, in pysam.libcfaidx.FastaFile.fetch
FileNotFoundError: [Errno 2] b'No such file or directory'
```

**Comment by theferrit32** [comment]
URL in question:
https://normalization.clingen.app/variation/parsed_to_abs_cnv?untranslatable_returns_text=true&assembly=GRCh37&chr=15&start=71597090&end=71853137&total_copies=1

Not replicable running one-off request. Returns 200 and correct response. Given it's a filesystem issue and seems to only happen when doing a large number of parallel requests, it may be related to seqrepo file descriptors again.

**Comment by theferrit32** [comment]
The bgzf exception I think is from a different request, but it's hard to tell in the log, exceptions aren't caught and logged alongside the input params.

That one happened multiple times and later seems to have caused a segfault. seqrepo interfaces with bgzf native libraries to get sequences out of those gzip files, so probably also seqrepo related.

```
INFO:     35.191.0.144:55663 - "GET /variation/to_canonical_variation?q=NC_000004.12%3Ag.54280489G%3EC&fmt=hgvs&untranslatable_returns_text=true HTTP/1.1" 200 OK
INFO:     35.191.18.155:59145 - "GET /variation/to_canonical_variation?q=NC_000013.11%3Ag.20222136G%3EA&fmt=hgvs&untranslatable_returns_text=true HTTP/1.1" 200 OK
INFO:     35.191.10.136:53919 - "GET /variation/to_canonical_variation?q=NC_000014.9%3Ag.23396270T%3EG&fmt=hgvs&untranslatable_returns_text=true HTTP/1.1" 200 OK
INFO:     35.191.10.136:49425 - "GET /variation/to_canonical_variation?q=NC_000017.11%3Ag.44908072delC&fmt=hgvs&untranslatable_returns_text=true HTTP/1.1" 200 OK
INFO:     35.191.1.248:56947 - "GET /variation/to_canonical_variation?q=clinvar%3A157133&fmt=hgvs&untranslatable_returns_text=true HTTP/1.1" 200 OK
INFO:     35.191.27.210:49728 - "GET /variation/to_canonical_variation?q=NC_000023.11%3Ag.13735278_13735279delAG&fmt=hgvs&untranslatable_returns_text=true HTTP/1.1" 200 OK
INFO:     35.191.2.138:60212 - "GET /variation/to_canonical_variation?q=NC_000008.11%3Ag.27460343delG&fmt=hgvs&untranslatable_returns_text=true HTTP/1.1" 200 OK
INFO:     35.191.1.245:53619 - "GET /variation/to_canonical_variation?q=NC_000005.10%3Ag.112754998del&fmt=hgvs&untranslatable_returns_text=true HTTP/1.1" 200 OK
INFO:     35.191.0.205:57967 - "GET /variation/to_canonical_variation?q=clinvar%3A5069&fmt=hgvs&untranslatable_returns_text=true HTTP/1.1" 200 OK
INFO:     35.191.28.38:57033 - "GET /variation/to_canonical_variation?q=NC_000001.11%3Ag.201076951del&fmt=hgvs&untranslatable_returns_text=true HTTP/1.1" 200 OK
INFO:     35.191.22.130:62988 - "GET /variation/to_canonical_variation?q=NC_000015.10%3Ag.48412639_48412640delTT&fmt=hgvs&untranslatable_returns_text=true HTTP/1.1" 200 OK
INFO:     130.211.1.218:59662 - "GET /variation/to_canonical_variation?q=NC_000007.14%3Ag.117531034delC&fmt=hgvs&untranslatable_returns_text=true HTTP/1.1" 200 OK
INFO:     35.191.28.46:63472 - "GET /variation/to_canonical_variation?q=NC_000007.14%3Ag.74069201_74069202insA&fmt=hgvs&untranslatable_returns_text=true HTTP/1.1" 200 OK
INFO:     35.191.2.234:62592 - "GET /variation/to_canonical_variation?q=clinvar%3A419946&fmt=hgvs&untranslatable_returns_text=true HTTP/1.1" 200 OK
INFO:     35.191.18.149:53844 - "GET /variation/to_canonical_variation?q=clinvar%3A226369&fmt=hgvs&untranslatable_returns_text=true HTTP/1.1" 200 OK
INFO:     35.191.2.132:32770 - "GET /variation HTTP/1.1" 200 OK
INFO:     35.191.10.139:61348 - "GET /variation/to_canonical_variation?q=NC_000019.9%3Ag.7594062dupT&fmt=hgvs&untranslatable_returns_text=true HTTP/1.1" 200 OK
INFO:     35.191.0.202:64426 - "GET /variation/to_canonical_variation?q=NC_000017.11%3Ag.43091805dup&fmt=hgvs&untranslatable_returns_text=true HTTP/1.1" 200 OK
INFO:     35.191.2.131:58649 - "GET /variation/hgvs_to_relative_copy_number?hgvs_expr=NC_000008.10%3Ag.%28%3F_17592647%29_%2817859657_%3F%29dup&relative_copy_class=EFO%3A0030070&untranslatable_returns_text=true HTTP/1.1" 200 OK
INFO:     130.211.0.55:55930 - "GET /variation/parsed_to_abs_cnv?untranslatable_returns_text=true&assembly=GRCh37&chr=4&start=12440&end=49064044&total_copies=3 HTTP/1.1" 200 OK
INFO:     35.191.27.220:54203 - "GET /variation/parsed_to_abs_cnv?untranslatable_returns_text=true&assembly=NCBI36&chr=4&start=66421303&end=66564659&total_copies=1 HTTP/1.1" 200 OK
[E::bgzf_uncompress] Inflate operation failed: invalid distance too far back
[E::fai_retrieve] Failed to retrieve block. (Seeking in a compressed, .gzi unindexed, file?)
Segmentation fault (core dumped)
```

**Comment by theferrit32** [comment]
Restarted the `clingen-vicc` chart with 5 `variation-normalizer` pods each with 1 worker thread. Deleted the persistent volumes so they would be repopulated from the targz file in google cloud storage. Ran the 10x curl line above and it immediately had the pysam file not found exception
```
…
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/biocommons/seqrepo/fastadir/fabgz.py", line 67, in fetch
    return self._fh.fetch(seq_id.encode("ascii"), start, end)
  File "pysam/libcfaidx.pyx", line 317, in pysam.libcfaidx.FastaFile.fetch
FileNotFoundError: [Errno 2] b'No such file or directory'
```

**Comment by theferrit32** [comment]
Same curl command with the same variant, additional exception discovered on one of the pods:
```
INFO:     35.191.1.247:51380 - "GET /variation/parsed_to_abs_cnv?untranslatable_returns_text=true&assembly=GRCh37&chr=7&start=74016832&end=74133273&total_copies=3 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "./variation/main.py", line 584, in parsed_to_abs_cnv
    resp = query_handler.to_copy_number_handler.parsed_to_abs_cnv(
  File "./variation/to_copy_number_variation.py", line 263, in parsed_to_abs_cnv
    self.seqrepo_access.seqrepo_client[accession][end]
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/biocommons/seqrepo/seqrepo.py", line 55, in __getitem__
    return self._fetch(key.start, key.stop)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/biocommons/seqrepo/seqrepo.py", line 42, in _fetch
    return self._sr.sequences.fetch(seq_id, start, end)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/biocommons/seqrepo/fastadir/fastadir.py", line 122, in fetch
    return fabgz.fetch(seq_id, start, end)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/biocommons/seqrepo/fastadir/fabgz.py", line 67, in fetch
    return self._fh.fetch(seq_id.encode("ascii"), start, end)
  File "pysam/libcfaidx.pyx", line 317, in pysam.libcfaidx.FastaFile.fetch
BlockingIOError: [Errno 11] b'Resource temporarily unavailable'
```

**Comment by theferrit32** [comment]
The fix applied is tracked here: https://github.com/cancervariants/variation-normalization/pull/388

**Comment by theferrit32** [comment]
We are running the branch in the PR above, closing this issue
